name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        RELEASE_TAG: ${{ github.ref_name }}
      run: docker build -t jurimullercloud/md2medium-publisher:$RELEASE_TAG .
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: jurimullercloud
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker Push
      env:
        RELEASE_TAG: ${{ github.ref_name }}
      run: docker push jurimullercloud/md2medium-publisher:$RELEASE_TAG
