name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Build version
      run: echo "RELEASE_VERSION=${github.event.release.tag_name}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build -t jurimullercloud/md2medium:$(env.RELEASE_VERSION) .
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: jurimullercloud
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_PASSWORD}}
    - name: Docker Push
      run: docker push jurimullercloud:$(env.RELEASE_VERSION)
